### ISSUE TITLE
QueryFailedError: column cnst.consrc does not exist error when seeding/running server with Postgres12

### ISSUE THREAD

**Issue by johannott** [alexitaylor/angular-graphql-nestjs-postgres-starter-kit#44]
Trying to seed the database or start the backend server gives the following error. 

I believe it is related to the Postgres version. Issue is introduced after Postgres 11.5.

```
QueryFailedError: column cnst.consrc does not exist
    at new QueryFailedError (/Users/johannott/Documents/Dev/dev/angular-postgres-starter/server/project/src/error/QueryFailedError.ts:9:9)
    at Query.callback (/Users/johannott/Documents/Dev/dev/angular-postgres-starter/server/project/src/driver/postgres/PostgresQueryRunner.ts:178:30)
    at Query.handleError (/Users/johannott/Documents/Dev/dev/angular-postgres-starter/server/project/node_modules/pg/lib/query.js:142:17)
    at Connection.connectedErrorMessageHandler (/Users/johannott/Documents/Dev/dev/angular-postgres-starter/server/project/node_modules/pg/lib/client.js:211:17)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:442:20)
    at Socket.<anonymous> (/Users/johannott/Documents/Dev/dev/angular-postgres-starter/server/project/node_modules/pg/lib/connection.js:126:12)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
^C
```

```
error: { error: column cnst.consrc does not exist
    at Connection.parseE (/Users/johannott/Documents/Dev/dev/angular-postgres-starter/server/project/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/Users/johannott/Documents/Dev/dev/angular-postgres-starter/server/project/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/Users/johannott/Documents/Dev/dev/angular-postgres-starter/server/project/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 196,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint:
   'Perhaps you meant to reference the column "cnst.conkey" or the column "cnst.conbin".',
  position: '194',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
```

**Comment by joeslee** [comment]
Maybe some of the dependencies are out of date.  I solved this problem by running `npx npm-check-updates -u`.
